# Generated by Django 3.2.5 on 2022-06-07 11:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0005_auto_20220607_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 11, 47, 49, 686423, tzinfo=utc)),
        ),
    ]
