# Generated by Django 3.2.5 on 2022-06-07 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0007_alter_product_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 7, 12, 58, 22, 671329, tzinfo=utc)),
        ),
    ]
