# Generated by Django 3.2.5 on 2022-06-08 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0008_alter_product_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 8, 12, 31, 53, 958188, tzinfo=utc)),
        ),
    ]
