# Generated by Django 3.2.5 on 2022-06-09 08:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0012_auto_20220609_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 8, 2, 49, 833557, tzinfo=utc)),
        ),
    ]
