# Generated by Django 3.2.5 on 2022-06-09 23:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0015_auto_20220610_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 9, 23, 55, 29, 947421, tzinfo=utc)),
        ),
    ]
